Module2 task1
htmlacademy-php1/51061-readme-13 pull request #3
Opened 2021-07-30 11:49 UTC by gladk0ff

![image](https://user-images.githubusercontent.com/17857839/127648835-1e8f55ed-90d9-4281-aa12-ea8cc2e42fc7.png)

2021-07-30 17:13 UTC, mihan007 requested changes
доработаем

2021-07-30 17:13 UTC, mihan007 commented on index.php
> +            <article class="popular__post post <?= $post['type']?>">
немного разнобой. выше ты отдельно вытягиваешь $content и $title, а тут `$post['type']`. надо единообразно.

2021-07-30 17:13 UTC, mihan007 commented on index.php
> +        foreach ($posts as $post) {
я рекомендую использовать `<?php foreach ($posts as $post): ?>` и не использовать `{` в шаблонах. с этими скобочками очень легко запутаться.

2021-07-30 17:13 UTC, mihan007 commented on index.php
> +            $content =$post['content'];
и подобные конструкции отдельно на каждой строке держу
```
<?php $content =$post['content']; ?>
<?php $title =$post['title']; ?>
```

2021-07-30 17:13 UTC, mihan007 commented on index.php
> +                        <div class="post-link__wrapper">
я не знаю, что рекомендуют создатели курса, но дичь с этим switch полная. я бы вынес каждую ветку этой конструкции в отдельный template. это будет легко поддерживать и воспринимать.

2021-08-02 12:58 UTC, mihan007 requested changes
Отличная работа! Понравилось, что распилил посты по типам в файла. Немного доделаем - PSR-12 и названия переменных посмотрим

2021-08-02 12:58 UTC, mihan007 commented on index.php
> +$posts=[
я тут записывал твоему коллеге видео про стандарты форматирования кода PSR-12. Это индустриальный стандарт PHP для внешнего вида кода.

Прошу его внедрить в проект и этот PR вернуть уже с ним.
Тут рассказано как: https://www.loom.com/share/02e337c29d0c44b48e987d552a7a97b6

2021-08-02 12:58 UTC, mihan007 commented on index.php
> +                    case "post-link":
отлично получилось, молодцом!

2021-08-02 12:58 UTC, mihan007 commented on index.php
> +                                <img class="post__author-avatar" src="img/<?= $post['avatar'] ?>" alt="Аватар пользователя">
тут опять вылезли конструкции вида `$post[поле]`. а выше мы их в отдельные переменные записали. выбери один вариант, это упростит дальнейшую работу. я бы оставил `$post['avatar']` и остальное в том же духе. не вижу смысла их на переменные потрошить

2021-08-02 12:58 UTC, mihan007 commented on index.php
> +                                <b class="post__author-name"><?= $post['user-name'] ?></b>
в названии ключей массива не рекомендую использовать тире. общий подход - чтобы из имени ключа можно было переменную создать. так работает https://www.php.net/manual/ru/function.compact.

а в твоем случае переменную `$user-name` создать то можно, наверное, но она нарушает стиль именования переменных. я бы выбрал `$user_name`. это стиль snake case, когда слова в переменной разделяются подчеркиванием.

посмотри такие слова как camelCase, snake_case, PascalCase - они все об одном - о стиле именования. Важно их знать и в рамках одного проекта придерживаться одного стиля

2021-08-02 12:58 UTC, mihan007 commented on templates/post/video.php
> +<?php require('helpers.php'); ?>
1. скорее всего, у тебя этот файл уже подключен в коде программы и здесь не нужен
2. используй всегда require_once - тебе лишь один раз нужно файл подключать ведь

2021-08-03 19:33 UTC, gladk0ff commented on index.php
> +$posts=[
принято внедрил)

2021-08-03 20:01 UTC, gladk0ff commented on index.php
> +                                <b class="post__author-name"><?= $post['user-name'] ?></b>
принято) за compact пасиб через нее нашел деструктуризацию в php

2021-08-03 20:03 UTC, gladk0ff commented on templates/post/video.php
> +<?php require('helpers.php'); ?>
+

2021-08-04 08:09 UTC, mihan007 requested changes
Еще чуть-чуть: сделаем автокомплит и поправим переносы после <?php в шаблонах - их быть не должно

2021-08-04 08:09 UTC, mihan007 commented on helpers.php
> +    set_error_handler(function () {
это зачем?

2021-08-04 08:09 UTC, mihan007 commented on index.php
> +            <?php
лучше на одной строке `<?php endif ?>` - читается и воспринимается легче

2021-08-04 08:09 UTC, mihan007 commented on index.php
> +                <?php
на одной строке

2021-08-04 08:09 UTC, mihan007 commented on index.php
> +                extract($post); ?>
чтобы он у тебя видел переменные можно **в начале** шаблона сделать так
```
<?php
/**
/* @var string $title
/* @var string $content
**/ 
?>
```
то есть выписать все переменные, которые вытащит extract. это даст тебе автодополнение в IDE

2021-08-04 08:09 UTC, mihan007 commented on index.php
> +            <?php
одна строка

2021-08-04 08:09 UTC, mihan007 commented on index.php
> +            <?php
![2021-08-04 at 11 07](https://user-images.githubusercontent.com/939122/128145682-3863311f-c9e7-4796-8ad7-8ffd18f56131.png)

2021-08-04 16:27 UTC, gladk0ff commented on index.php
> +                extract($post); ?>
вернул изначальное как  в телеге порешали

2021-08-04 16:28 UTC, gladk0ff commented on helpers.php
> +    set_error_handler(function () {
ммм хз) видимо psr 12 тело функции перенес на новую строку) я не деляль)

2021-08-05 15:23 UTC, mihan007 approved these changes
Perfect!

2021-08-05 15:23 UTC, merged