Module2 task2
htmlacademy-php1/51061-readme-13 pull request #4
Opened 2021-07-30 15:27 UTC by gladk0ff

![image](https://user-images.githubusercontent.com/17857839/127675736-1ec6adf7-89fd-40c1-9cbb-337a1945549b.png)

2021-08-06 04:48 UTC, mihan007 requested changes
Хорошо получилось. Немного форматирование подрихтуем и уберем magic numbers в коде

Для развития рекомендую посмотреть как похожая функция реализована в мегапопулярном Laravel
1. Функция обрезания текста по количеству символов https://github.com/illuminate/support/blob/master/Str.php#L356. Тут хитро - функция понимает ширину текста по ширине букв
2. Функция обрезания по количеству слов https://github.com/illuminate/support/blob/master/Str.php#L384. Там регулярка зубодробительная
3. Еще полезно почитать обзор других функций Laravel и в коде их посмотреть https://dev.to/aschmelyun/my-favorite-laravel-helpers-and-how-to-use-them-28ij

Я **очень** рекомендую читать исходники популярных php пакетов. Развивает фантастически

2021-08-06 04:48 UTC, mihan007 commented on helpers.php
> + * текст, если его длина меньше заданного числа(по умолчанию 300) символов. В противном случае это должен быть урезанный текст с прибавленной к нему ссылкой.
Поработаем с форматированием кода
1. Сперва поправим эту галочку
![2021-08-06 at 07 31](https://user-images.githubusercontent.com/939122/128456303-0357769b-f546-42ca-ae39-2450250f1700.png)
2. Переходим на PSR-12 - индустриальный стандарт программирования на PHP. См видео https://www.loom.com/share/02e337c29d0c44b48e987d552a7a97b6

**Для чего**
- Единый стандарт кода позволяет легко развивать его в рамках команды. Глаз каждого участника привыкает к внешнему виду конструкций и усилия мозга работают только на понимание сути.
- Если код оформляется единообразно, то Code Review делать легче. Проверяющий видит только изменения по делу и не видит изменений из-за всяких отступов и переносов строк.

2021-08-06 04:48 UTC, mihan007 commented on helpers.php
> +function is_need_trunc(string $text,int $length=300):bool {
отлично, что в отдельную функцию вынес. логика действительно может быть разной и хорошо в одном месте это контролировать

2021-08-06 04:48 UTC, mihan007 commented on helpers.php
> +        if ($symbol_count >300) {
тут, видимо, надо использовать параметр функции вместо хардкода 300

2021-08-06 04:48 UTC, mihan007 commented on helpers.php
> +        $symbol_count = $symbol_count + strlen($word);
подумай насчет использования `mb_strlen` - это нужно для корректной работы функции с языками, отличными от английского

2021-08-06 04:48 UTC, mihan007 commented on templates/post/text.php
> +
- docblock немного не так оформлен, ты присылал верный вариант
- пробел после docblock не нужен

2021-08-10 19:52 UTC, gladk0ff commented on helpers.php
> + * текст, если его длина меньше заданного числа(по умолчанию 300) символов. В противном случае это должен быть урезанный текст с прибавленной к нему ссылкой.
![image](https://user-images.githubusercontent.com/17857839/128925807-13af5080-59f2-48f1-8667-642b112e074d.png)
это по первому)
по второму как бы с Того пр в нем - пока не понимаю что не так =(

2021-08-10 19:53 UTC, gladk0ff commented on helpers.php
> +        if ($symbol_count >300) {
ОДНОЗНАЧНО)

2021-08-10 19:57 UTC, gladk0ff commented on helpers.php
> +        $symbol_count = $symbol_count + strlen($word);
mb_strlen - почитал выглядит понадежней ) спасибо за подгон

2021-08-10 20:01 UTC, gladk0ff commented on templates/post/text.php
> +
принято)

2021-08-12 04:12 UTC, mihan007 approved these changes
Чудесно поработал!

2021-08-12 04:12 UTC, merged