add sql scheme
htmlacademy-php1/51061-readme-13 pull request #7
Opened 2021-08-29 19:08 UTC by gladk0ff

2021-08-30 07:58 UTC, mihan007 requested changes
Привет, Андрей!
Классно поработал. Есть ряд предложений, изучи, пожалуйста.

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  register_day TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
- я рекомендую для всех сущностей добавлять поля created_at и updated_at. это решает задачи - узнать, когда была создана сущность, когда изменена. эта информация нужна очень часто
- created_at должен заполняться БД автоматически при добавлении сущности в БД
- updated_at изменяется БД при изменении записи. При создании сущности его удобнее заполнять также как и created_at
- и тут как раз created_at даст нам дату регистрации пользователя

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE user
принято таблицы называть в множественном числе, так удобнее

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  email        VARCHAR(128) NOT NULL,
320 символов может быть по доке.

length limit on email addresses. That limit is a maximum of 64 characters (octets) in the "local part" (before the "@") and a maximum of 255 characters (octets) in the domain part (after the "@") for a total length of 320
https://www.rfc-editor.org/errata/eid1690

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  password     CHAR(64)     NOT NULL,
не скупись на длину пароля)) 255 лучше

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE message
- множественное
- created_at и updated_at

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  create_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
это заменится created_at

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  CONSTRAINT check_icon_class CHECK
- это интересный подход, ни разу не делал. не рекомендую так делать. лучше здесь int и вставлять обычные цифры. а на уровне приложения ты уже будешь маппить эти цифры на имя класса
- почему? если ты будешь добавлять новый тип класса и используешь текущий подход, то тебе поверх базы придется запускать sql, который изменит таблицу для нового типа поста. пока он меняет таблица заблокирована и часть пользователей не смогут сервис использовать. это не очень
- см http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  create_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
заменит created_at

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE types
- вот тут ты в множественном числе назвал, это верно
- created_at и updated_at добавь сюда, пожалуйста

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE posts
- created_at и updated_at добавь сюда, пожалуйста

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  title           TEXT NOT NULL,
вряд ли заголовок будет длинным текстом, я бы varchar на 255 символов поставил. Хватит за глаза

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  img_url         TEXT,
- url это 2048 символов, text тут избыточен
- не скупись на буквы. image_url легче запомнить и вспомнить. упрощай.

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  video_url       TEXT,
- url это 2048 символов, text тут избыточен

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  link            TEXT,
у тебя ссылка везде названо верно - url. url и тут используй с 2048 символами

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_at и друг его updated_at

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE subscription
множественное число

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  id           INT AUTO_INCREMENT PRIMARY KEY,
тут не надо. у тебя уникальный составной ключ (author_id, subscription**_id**) - это позволит не множить записи о том, на что юзер подписался

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +CREATE TABLE hashtag
множественное

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  post_id INT,
это не надо, у тебя это просто таблица тегов

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +  FOREIGN KEY (post_id) REFERENCES posts (id)
created_at и друг его updated_at

2021-08-30 07:58 UTC, mihan007 commented on sсhema.sql
> +
Свяжи hashtag и post отдельной таблицей, у тебя многие-ко-многим тут. Один хэштег может быть у сколько угодно постов. А один пост может содержать несколько хэштегов.

2021-08-30 19:11 UTC, gladk0ff commented on sсhema.sql
> +CREATE TABLE user
+

2021-08-30 19:12 UTC, gladk0ff commented on sсhema.sql
> +  email        VARCHAR(128) NOT NULL,
+

2021-08-30 19:13 UTC, gladk0ff commented on sсhema.sql
> +  password     CHAR(64)     NOT NULL,
не скупись))) ок)

2021-08-30 19:14 UTC, gladk0ff commented on sсhema.sql
> +CREATE TABLE message
+

2021-08-30 19:20 UTC, gladk0ff commented on sсhema.sql
> +  id           INT AUTO_INCREMENT PRIMARY KEY,
+

2021-08-30 19:21 UTC, gladk0ff commented on sсhema.sql
> +CREATE TABLE subscription
+

2021-08-30 19:30 UTC, gladk0ff commented on sсhema.sql
> +  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
))

2021-09-01 04:43 UTC, mihan007 approved these changes
Привет!
Спасибо за работу. Маленькие правки учти дальше, пожалуйста

2021-09-01 04:43 UTC, mihan007 commented on sсhema.sql
> +  update_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Updated_at

2021-09-01 04:43 UTC, mihan007 commented on sсhema.sql
> +  name       VARCHAR(100)
Для одушевлённых сущностей name, неодушевлённых - title

2021-09-01 04:43 UTC, merged